name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 180
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.4.0

      - name: Add repo deps
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  # Update the generated timestamp in the index.yaml
  # needed until https://github.com/helm/chart-releaser/issues/90
  # or helm/chart-releaser-action supports this
  post-release:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Commit and push timestamp updates
        run: |
          if [[ -f index.yaml ]]; then
            export generated_date=$(date --utc +%FT%T.%9NZ)
            sed -i -e "s/^generated:.*/generated: \"$generated_date\"/" index.yaml
            git add index.yaml
            git commit -sm "Update generated timestamp [ci-skip]" || exit 0
            git push
          fi
